name: "lightning-accounts-${NODE_ENV:-development}"

services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  server:
    depends_on:
      postgres:
        condition: service_healthy
    extends:
      file: docker-compose.base.yml
      service: server

volumes:
  node_modules:
