name: "lightning-accounts-staging"

include:
  - path: docker-compose.networks.yml

services:
  postgres:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.30.0.11
    extends:
      file: docker-compose.prod.yml
      service: postgres
  server:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.30.0.10
    extends:
      file: docker-compose.prod.yml
      service: server
    environment:
      APPLICATION_ADDRESS: "::ffff:10.30.0.1"
      DATABASE_URL: "postgresql://${NODE_DB_USER}:${NODE_DB_PASSWORD}@postgres:5432/${NODE_DB_NAME}?schema=public"
