services:
  backend1:
    image: polarlightning/bitcoind:24.0
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-rpcport=18443",
          "-rpcuser=polaruser",
          "-rpcpassword=polarpass",
          "getblockchaininfo",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    container_name: lightning-accounts-polar-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28336
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28334
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - "18443"
      - "18444"
      - "28334"
      - "28335"
    ports:
      - "18443:18443"
      - "19444:18444"
      - "28334:28334"
      - "29335:28335"
  alice:
    image: polarlightning/lnd:0.16.2-beta
    container_name: lightning-accounts-polar-alice
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice
      --tlsextradomain=alice --tlsextradomain=lightning-accounts-polar-alice
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=lightning-accounts-polar-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-polar-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-polar-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8081:8080"
      - "10001:10009"
      - "9735:9735"
  bob:
    image: polarlightning/clightning:23.02.2
    container_name: lightning-accounts-polar-bob
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bob
    command: >-
      lightningd --alias=bob --addr=bob --addr=0.0.0.0:9735 --network=regtest
      --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass
      --bitcoin-rpcconnect=lightning-accounts-polar-backend1 --bitcoin-rpcport=18443
      --log-level=debug --dev-bitcoind-poll=2 --dev-fast-gossip
      --grpc-port=11001 --plugin=/opt/c-lightning-rest/plugin.js
      --rest-port=8080 --rest-protocol=http
    restart: always
    volumes:
      - ./volumes/c-lightning/bob/lightningd:/home/clightning/.lightning
      - ./volumes/c-lightning/bob/rest-api:/opt/c-lightning-rest/certs
    expose:
      - "8080"
      - "11001"
      - "9735"
    ports:
      - "8182:8080"
      - "11002:11001"
      - "9836:9735"
  carol:
    image: polarlightning/lnd:0.16.2-beta
    container_name: lightning-accounts-polar-carol
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: carol
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=carol --externalip=carol
      --tlsextradomain=carol --tlsextradomain=lightning-accounts-polar-carol
      --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=lightning-accounts-polar-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-polar-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-polar-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8083:8080"
      - "10003:10009"
      - "9737:9735"
  dave:
    image: polarlightning/lnd:0.16.2-beta
    container_name: lightning-accounts-polar-dave
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: dave
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=dave --externalip=dave
      --tlsextradomain=dave --tlsextradomain=lightning-accounts-polar-dave --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=lightning-accounts-polar-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-polar-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-polar-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/dave:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8084:8080"
      - "10004:10009"
      - "9738:9735"
