services:
  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NODE_DB_USER} -d ${NODE_DB_NAME}"]
      interval: 5s
      start_period: 1s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${NODE_DB_NAME}
      POSTGRES_USER: ${NODE_DB_USER}
      POSTGRES_PASSWORD: ${NODE_DB_PASSWORD}
  server:
    build:
      context: .
      args:
        PORT: ${NODE_PORT}
    command: ["yarn", "start"]
    expose:
      - "${NODE_PORT}"
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - path: ./.env
    extra_hosts:
      - host.docker.internal:host-gateway

