name: "lightning-accounts-${NODE_ENV:-development}"

include:
  - path: docker-compose.networks.yml
  - path: docker-compose.lightning.yml

services:
  postgres_ln:
    extends:
      file: docker-compose.base.yml
      service: postgres
  server:
    volumes:
      - ./src:/opt/app/src
    command: ["yarn", "start:migrate"]
    environment:
      APPLICATION_ADDRESS: "::ffff:10.29.0.1"
      DATABASE_URL: "postgresql://${NODE_DB_USER}:${NODE_DB_PASSWORD}@postgres_ln:5432/${NODE_DB_NAME}?schema=public"
    depends_on:
      postgres_ln:
        condition: service_healthy
    extends:
      file: docker-compose.base.yml
      service: server
