services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  lightning-accounts:
    extends:
      file: docker-compose.base.yml
      service: lightning-accounts

volumes:
  node_modules:
