services:
  backend1:
    image: polarlightning/bitcoind:29.0
    container_name: lightning-accounts-${NODE_ENV:-test}-backend1
    healthcheck:
      test:
        [
          "CMD",
          "bitcoin-cli",
          "-rpcport=18443",
          "-rpcuser=polaruser",
          "-rpcpassword=polarpass",
          "getblockchaininfo"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: lightning-accounts-${NODE_ENV:-test}-backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=0 -zmqpubrawblock=tcp://0.0.0.0:28336
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28334
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - "18443"
      - "18444"
      - "28334"
      - "28335"
      - "28336"
    ports:
      - "18443:18443"
      - "19444:18444"
      - "28334:28334"
      - "28335:28335"
      - "28336:28336"
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.12

  alice:
    image: polarlightning/lnd:0.19.2-beta
    container_name: lightning-accounts-${NODE_ENV:-test}-alice
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: lightning-accounts-${NODE_ENV:-test}-alice
    healthcheck:
      test: ["CMD-SHELL", "test -f /home/lnd/.lnd/tls.cert && test -f /home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon && lncli --rpcserver=localhost:10009 --macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon --tlscertpath=/home/lnd/.lnd/tls.cert getinfo"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=lightning-accounts-${NODE_ENV:-test}-alice
      --tlsextradomain=10.29.0.13
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --allow-circular-route
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoin.timelockdelta=18
      --bitcoind.rpchost=lightning-accounts-${NODE_ENV:-test}-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28336
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8081:8080"
      - "10001:10009"
      - "9735:9735"
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.13

  bob:
    image: polarlightning/lnd:0.19.2-beta
    container_name: lightning-accounts-${NODE_ENV:-test}-bob
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: lightning-accounts-${NODE_ENV:-test}-bob
    healthcheck:
      test: ["CMD-SHELL", "test -f /home/lnd/.lnd/tls.cert && test -f /home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon && lncli --rpcserver=localhost:10009 --macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon --tlscertpath=/home/lnd/.lnd/tls.cert getinfo"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=lightning-accounts-${NODE_ENV:-test}-bob
      --tlsextradomain=10.29.0.14
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --allow-circular-route
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoin.timelockdelta=18
      --bitcoind.rpchost=lightning-accounts-${NODE_ENV:-test}-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28336
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/bob:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8085:8080"
      - "10005:10009"
      - "9739:9735"
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.14

  carol:
    image: polarlightning/lnd:0.19.2-beta
    container_name: lightning-accounts-${NODE_ENV:-test}-carol
    depends_on:
      backend1:
        condition: service_healthy
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: lightning-accounts-${NODE_ENV:-test}-carol
    healthcheck:
      test: ["CMD-SHELL", "test -f /home/lnd/.lnd/tls.cert && test -f /home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon && lncli --rpcserver=localhost:10009 --macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon --tlscertpath=/home/lnd/.lnd/tls.cert getinfo"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=carol --externalip=lightning-accounts-${NODE_ENV:-test}-carol
      --tlsextradomain=10.29.0.15
      --tlsextradomain=host.docker.internal --listen=0.0.0.0:9735
      --allow-circular-route
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoin.timelockdelta=18
      --bitcoind.rpchost=lightning-accounts-${NODE_ENV:-test}-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28336
      --bitcoind.zmqpubrawtx=tcp://lightning-accounts-${NODE_ENV:-test}-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/lnd/.lnd
    expose:
      - "8080"
      - "10009"
      - "9735"
    ports:
      - "8083:8080"
      - "10003:10009"
      - "9737:9735"
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.15