name: "lightning-accounts-staging"

include:
  - path: docker-compose.networks.yml

services:
  postgres:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.41
    extends:
      file: docker-compose.prod.yml
      service: postgres
  server:
    networks:
      lightningaccountsnet:
        ipv4_address: 10.29.0.40
    extends:
      file: docker-compose.prod.yml
      service: server
