name: "lightning-accounts-${NODE_ENV:-test}"

services:
  postgres_test:
    extends:
      file: docker-compose.base.yml
      service: postgres
  server:
    command: ["yarn", "start:e2e"]
    depends_on:
      postgres_test:
        condition: service_healthy
    env_file:
      - path: ./.env.test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: "postgresql://${NODE_DB_USER}:${NODE_DB_PASSWORD}@postgres_test:5432/${NODE_DB_NAME}?schema=public"
    extends:
      file: docker-compose.base.yml
      service: server

volumes:
  node_modules:
