services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  lightning-accounts:
    depends_on:
      postgres:
        condition: service_healthy
    extends:
      file: docker-compose.base.yml
      service: lightning-accounts

volumes:
  node_modules:
